### ISSUE TITLE
Uncertainty about SFT and DPO in Each Round of Model Iteration.

### ISSUE THREAD

**Issue by BaenRH** [facebookresearch/RAM#14]
In the paper self-taught evaluators, I would like to know if both SFT and DPO are used in each round of model iteration? According to the papers I read, only SFT is performed in each round. However, the flowchart in the README file seems to be different from the flowchart in the papers. There is an additional DPO step?

**Comment by xianxl** [comment]
You're right. In the paper, only SFT was used in each iteration.
