### ISSUE TITLE
Questions about Dataset Construction

### ISSUE THREAD

**Issue by d223302** [facebookresearch/RAM#15]
Thank you for this interesting work. I have two questions about the dataset construction process.
1. **Prompt selection**:  How are the released `facebook/Self-taught-evaluator-DPO-data` constructed? In Section 3.2 of the paper (Instruction Selection) and Section 4.1 (Experimental Setup), the paper says," _To perform prompt selection, we annotate the category of each instruction with the Mixtral 22Bx8 Instruct model, using the template in Figure 7 and select 20,582 examples in the reasoning category, as we expect these to be challenging inputs_". However, the released `facebook/Self-taught-evaluator-DPO-data` contains 56376 preference pairs and 6565 unique instructions, mismatching the dataset size in the paper. Is it possible to also share the selected 20,582 instructions?
2. **Response generation**: When generating the winning and losing responses used for LLM-as-a-judge, are those responses always generated by Mixtral 22Bx7 among all training iterations? Based on the paper, it seems that those winning and losing responses are fixed and always shared across training iterations. Is it possible to also share those winning and losing responses?

**Comment by xianxl** [comment]
1. The DPO data was constructed using the script as is described in https://github.com/facebookresearch/RAM/tree/main/projects/self_taught_evaluator#prepare-training-data. Note that DPO training is not used in the paper.
2. The response was only generated once and fixed during iterations. The responses were included in the released data, referred to as "Assistant A's Answer" and "Assistant B's Answer".
