### ISSUE TITLE
sft

### ISSUE THREAD

**Issue by suchenyang2023** [facebookresearch/RAM#18]
Thank you for your work. I am a bit confused about the "self-taught evaluator" part. How should I prepare data from scratch for SFT training, as the repo only provides DPO data?

**Comment by tianlu-wang** [comment]
Hi! Please check out our paper for details on creating SFT data. If you want to have something to quickly try SFT training, you may consider using "tgt_chosen" in our DPO data as the target sequences for SFT training.

**Comment by xianxl** [comment]
SFT training data generation is also described in https://github.com/facebookresearch/RAM/tree/main/projects/self_taught_evaluator#synthetic-preference-data.
