### ISSUE TITLE
Questions About Model Choice in the Self-Taught Evaluator

### ISSUE THREAD

**Issue by 12485953** [facebookresearch/RAM#21]
Hi, thank you for your excellent work! I have two questions regarding the self-taught evaluator:
1.**SFT Start Point:** I’ve noticed that in each iteration of the self-taught evaluator, the SFT begins with the seed model, rather than continuing fine-tuning from the model obtained in the previous iteration. Could you clarify the reasoning behind this approach? Is it intended to prevent the fine-tuned model from losing capabilities beyond judgement after multiple iterations of fine-tuning?
2.**Judgement Generation Model Choice:** In the first iteration, the Mixtral 22B*8 instruct model was used to generate judgements, instead of the seed model, Llama-3-70B Instruct. Could you explain why this choice was made? Would there be any potential issues, such as reduced data quality, if Llama-3-70B Instruct had been used to generate judgements in the first iteration?

**Comment by tianlu-wang** [comment]
Hi, thanks for your questions. 
Regarding the starting point for SFT, we have empirically found that beginning with the seed model yields better results than starting from the model obtained in the previous iteration.
For judgment generation, either the Mixtral or LLaMA models can be used interchangeably.
